"""EHS form registry — ported 1:1 from metfraa-ehs forms-config.js.

Single source of truth: forms render from this config and submissions are
validated against it. 6 general forms + 15 equipment inspection checklists.
Edit ONLY this file to add/change a form.
"""

APPROVERS = ['Varadharaj', 'Nirmal Kumar']

# Employees whose email is here (or is_admin) can approve/reject EHS submissions.
# Override with EHS_APPROVER_EMAILS env var (comma-separated).
APPROVER_EMAILS = ['varadharaj@metfraa.com', 'nirmal@metfraa.com']

INSPECTORS = ['Varadharaj', 'Nirmal Kumar']

ALL_FORMS = [{'id': 'toolbox',
  'code': 'TBT',
  'title': 'Toolbox Talk',
  'category': 'general',
  'folder': '01-Toolbox-Talks',
  'icon': '🛠️',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'participants',
              'label': 'No. of Persons Participated',
              'type': 'number',
              'required': True,
              'min': 1},
             {'key': 'date', 'label': 'Date', 'type': 'date', 'required': True, 'autofill': 'today'},
             {'key': 'time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'location', 'label': 'Location', 'type': 'text', 'required': True},
             {'key': 'topics_covered', 'label': 'Topics Covered', 'type': 'textarea', 'required': True},
             {'key': 'conducted_by', 'label': 'Conducted By', 'type': 'inspector', 'required': True},
             {'key': 'tbt_photo', 'label': 'TBT Conducted Photo', 'type': 'photo', 'required': True},
             {'key': 'attendance_sheet',
              'label': 'TBT Attendance Sheet',
              'type': 'photo',
              'required': True}]},
 {'id': 'induction',
  'code': 'IND',
  'title': 'Induction',
  'category': 'general',
  'folder': '02-Induction',
  'icon': '👷',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'project_location', 'label': 'Project Location', 'type': 'text', 'required': True},
             {'key': 'induction_date',
              'label': 'Date of Induction',
              'type': 'date',
              'required': True,
              'autofill': 'today'},
             {'key': 'employee_name', 'label': 'Employee / Worker Name', 'type': 'text', 'required': True},
             {'key': 'contractor_name',
              'label': 'MSB / Sub-Contractor Name',
              'type': 'text',
              'required': True},
             {'key': 'emergency_contact',
              'label': 'Emergency Contact Number',
              'type': 'tel',
              'required': True,
              'pattern': '[0-9+\\- ]{7,15}'},
             {'key': 'father_name', 'label': 'Father Name', 'type': 'text', 'required': True},
             {'key': 'dob', 'label': 'Date of Birth', 'type': 'date', 'required': True},
             {'key': 'aadhaar_photo',
              'label': 'Aadhaar Card Pic (Front & Back)',
              'type': 'photo',
              'required': True,
              'multiple': True},
             {'key': 'induction_document', 'label': 'Induction Document', 'type': 'photo', 'required': True},
             {'key': 'conducted_by', 'label': 'Conducted By', 'type': 'inspector', 'required': True}]},
 {'id': 'ehs-audit',
  'code': 'AUD',
  'title': 'EHS Audit',
  'category': 'general',
  'folder': '03-EHS-Audit',
  'icon': '🔍',
  'fields': [{'key': 'audit_date',
              'label': 'Audit Conducted Date',
              'type': 'date',
              'required': True,
              'autofill': 'today'},
             {'key': 'auditee', 'label': 'Auditee', 'type': 'inspector', 'required': True},
             {'key': 'site_name', 'label': 'Site Name', 'type': 'project', 'required': True},
             {'key': 'exact_location', 'label': 'Exact Location', 'type': 'text', 'required': True},
             {'key': 'observation', 'label': 'Observation', 'type': 'textarea', 'required': True},
             {'key': 'photo_evidence',
              'label': 'Photographic Evidence',
              'type': 'photo',
              'required': True,
              'multiple': True},
             {'key': 'category',
              'label': 'Category',
              'type': 'select',
              'required': True,
              'options': ['Unsafe Acts', 'Unsafe Conditions', 'Dangerous Occurrences']},
             {'key': 'corrective_action', 'label': 'Corrective Action', 'type': 'textarea', 'required': True},
             {'key': 'preventive_action', 'label': 'Preventive Action', 'type': 'textarea', 'required': True},
             {'key': 'responsible_person', 'label': 'Responsible Person', 'type': 'text', 'required': True},
             {'key': 'target_date', 'label': 'Target Date', 'type': 'date', 'required': True}]},
 {'id': 'incident',
  'code': 'INC',
  'title': 'Incident / Accident Report',
  'category': 'general',
  'folder': '04-Incident-Reports',
  'icon': '⚠️',
  'fields': [{'key': 'site_name', 'label': 'Site Name', 'type': 'project', 'required': True},
             {'key': 'incident_date', 'label': 'Date of Incident', 'type': 'date', 'required': True},
             {'key': 'incident_time', 'label': 'Time of Incident', 'type': 'time', 'required': True},
             {'key': 'area_location', 'label': 'Area / Location', 'type': 'text', 'required': True},
             {'key': 'subcontractor_name',
              'label': 'Name of Subcontractor',
              'type': 'text',
              'required': True},
             {'key': 'injured_person_name', 'label': 'Injured Person Name', 'type': 'text', 'required': True},
             {'key': 'designation', 'label': 'Designation', 'type': 'text', 'required': True},
             {'key': 'incident_type',
              'label': 'Incident Type',
              'type': 'select',
              'required': True,
              'options': ['First Aid',
                          'Medical',
                          'Fatal',
                          'Near Miss',
                          'Dangerous Occurrence',
                          'Property Damage',
                          'Environmental']},
             {'key': 'accident_type',
              'label': 'Accident Type',
              'type': 'radio',
              'required': True,
              'options': ['Major', 'Minor', 'Near Miss']},
             {'key': 'injury_details', 'label': 'Injury Details', 'type': 'textarea', 'required': True},
             {'key': 'equipment_name',
              'label': 'Name / Identity of P&M / Equipment',
              'type': 'text',
              'required': False},
             {'key': 'equipment_owned_by',
              'label': 'Equipment Owned By',
              'type': 'select',
              'required': False,
              'options': ['MSBPL', 'Sub-contractor', 'N/A']},
             {'key': 'return_to_work_date',
              'label': 'Return-to-Work Date (if known)',
              'type': 'date',
              'required': False},
             {'key': 'incident_description',
              'label': 'What Happened — Brief Description',
              'type': 'textarea',
              'required': True},
             {'key': 'root_cause', 'label': 'Root Cause', 'type': 'textarea', 'required': True},
             {'key': 'preventive_actions',
              'label': 'Preventive Actions Taken',
              'type': 'textarea',
              'required': True},
             {'key': 'corrective_actions',
              'label': 'Immediate Corrective Actions Taken',
              'type': 'textarea',
              'required': True},
             {'key': 'incident_photo',
              'label': 'Incident Photo',
              'type': 'photo',
              'required': True,
              'multiple': True},
             {'key': 'investigation_team',
              'label': 'Names & Designation of Investigation Team',
              'type': 'textarea',
              'required': True},
             {'key': 'prepared_by', 'label': 'Prepared By', 'type': 'inspector', 'required': True}]},
 {'id': 'hse-meeting',
  'code': 'HSE',
  'title': 'HSE Meeting',
  'category': 'general',
  'folder': '05-HSE-Meetings',
  'icon': '👥',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'project_location', 'label': 'Project Location', 'type': 'text', 'required': True},
             {'key': 'no_of_persons',
              'label': 'No. of Persons',
              'type': 'number',
              'required': True,
              'min': 1},
             {'key': 'meeting_no', 'label': 'Meeting No.', 'type': 'text', 'required': True},
             {'key': 'date', 'label': 'Date', 'type': 'date', 'required': True, 'autofill': 'today'},
             {'key': 'time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'attendance_sheet', 'label': 'Attendance Sheet', 'type': 'photo', 'required': True},
             {'key': 'meeting_photo', 'label': 'Meeting Photo', 'type': 'photo', 'required': True},
             {'key': 'no_of_points',
              'label': 'No. of Points Discussed',
              'type': 'number',
              'required': True,
              'min': 1},
             {'key': 'mom_points',
              'label': 'Minutes of Meeting (MoM) Points',
              'type': 'photo',
              'required': True,
              'multiple': True},
             {'key': 'prepared_by', 'label': 'Prepared By', 'type': 'inspector', 'required': True}]},
 {'id': 'permit-record',
  'code': 'PR',
  'title': 'Permit Record',
  'category': 'general',
  'folder': '07-Permit-Records',
  'icon': '📋',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'date', 'label': 'Date', 'type': 'date', 'required': True, 'autofill': 'today'},
             {'key': 'time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'work_location', 'label': 'Exact Location of Work', 'type': 'text', 'required': True},
             {'key': 'work_description', 'label': 'Work Description', 'type': 'textarea', 'required': True},
             {'key': 'permit_no', 'label': 'Permit No.', 'type': 'text', 'required': True},
             {'key': 'permit_type',
              'label': 'Type of Permit',
              'type': 'radio',
              'required': True,
              'options': ['Height Work Permit',
                          'Hot Work Permit',
                          'Night Work Permit',
                          'Shuttering & Deshuttering Permit',
                          'General Work Permit',
                          'Loading & Unloading Work Permit']},
             {'key': 'hse_officer', 'label': 'HSE Officer', 'type': 'inspector', 'required': True}]},
 {'id': 'portable-grinding-machine',
  'code': 'PGM',
  'title': 'Portable Grinding Machine',
  'category': 'equipment',
  'folder': '06-Equipment-Inspections/Portable-Grinding-Machine',
  'icon': '⚙️',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'inspection_date',
              'label': 'Date of Inspection',
              'type': 'date',
              'required': True,
              'autofill': 'today'},
             {'key': 'inspection_time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'equipment_no', 'label': 'Equipment No.', 'type': 'text', 'required': True},
             {'key': 'equipment_photo',
              'label': 'Inspected Equipment Photo',
              'type': 'photo',
              'required': True},
             {'key': 'inspected_by', 'label': 'Inspected By', 'type': 'inspector', 'required': True}],
  'checklist': ['Fore handle without damage',
                'Grinding wheel without any crack',
                'Wheel guard',
                'Rear handle without any damage',
                'Presence of cord strain reliever (glands)',
                'Trigger switch without damage',
                'Presence of switch lock',
                'Electric wire without cuts and joints']},
 {'id': 'gas-welding-set',
  'code': 'GWS',
  'title': 'Gas Welding Set',
  'category': 'equipment',
  'folder': '06-Equipment-Inspections/Gas-Welding-Set',
  'icon': '🔥',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'inspection_date',
              'label': 'Date of Inspection',
              'type': 'date',
              'required': True,
              'autofill': 'today'},
             {'key': 'inspection_time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'equipment_no', 'label': 'Equipment No.', 'type': 'text', 'required': True},
             {'key': 'equipment_photo',
              'label': 'Inspected Equipment Photo',
              'type': 'photo',
              'required': True},
             {'key': 'inspected_by', 'label': 'Inspected By', 'type': 'inspector', 'required': True}],
  'checklist': ['Protective valve cap firmly fixed for both cylinders (check for damage/crack in the valve '
                'cap)',
                'Flash back arrestor (FBAs) provided for acetylene & oxygen cylinders',
                'Pressure gauges (two for each cylinder, inlet & outlet) in working condition (both Oxygen & '
                'Acetylene gas)',
                'Non-return valves (NRVs) provided for both acetylene & oxygen cylinders',
                'Tight crimping of hoses with jubilee clamps',
                'Hose free from damage (cuts and cracks)',
                'Cylinder secured by chain to the trolley',
                'Trolley tyres free from damages',
                'Availability of industrial-type lighter (no match-box / commercial lighters)']},
 {'id': 'aerial-boomlift',
  'code': 'ABL',
  'title': 'Aerial Boomlift',
  'category': 'equipment',
  'folder': '06-Equipment-Inspections/Aerial-Boomlift',
  'icon': '🏗️',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'inspection_date',
              'label': 'Date of Inspection',
              'type': 'date',
              'required': True,
              'autofill': 'today'},
             {'key': 'inspection_time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'equipment_no', 'label': 'Equipment No.', 'type': 'text', 'required': True},
             {'key': 'equipment_photo',
              'label': 'Inspected Equipment Photo',
              'type': 'photo',
              'required': True},
             {'key': 'inspected_by', 'label': 'Inspected By', 'type': 'inspector', 'required': True}],
  'checklist': ['Wheels, Tyres & Axles — Condition / Inflation',
                'Hydraulic Components — Condition / Leaks',
                'Data Plate — Accurate / Legible',
                'Annual Inspection Verified',
                'Battery Tray — Opens / Closes easily, Latches Shut',
                'Turret turntable — Gears / Lockpin / Stops',
                'Counter Weight',
                'Cover Panels — Open / Close easily, Latch / Lock Shut',
                'Engine — Fluids / Filters / Belts / Hoses',
                'Batteries — Clean / Dry / Secure / Cap-Cables / Level',
                'Fuel Tank — Level',
                'Hydraulic Oil Level',
                'Lights & Strobes',
                'Placards / Labels / Decals — Legible',
                'Boom Valley — Leaks / Debris',
                'Accessory Plugs & Cables',
                'Boom — General condition / Wear',
                'Hydraulic Cylinders & Pin Locks',
                'Articulated Joints — Wear / Cracks',
                'Power Track — Lines & Hoses',
                'Platform — Guardrails / Toeboards / Anchorages',
                'Weather-Resistant Storage Compartment — Appropriate Manuals',
                'All Controls — Clearly Marked / Hold-to-Run',
                'Engine — Starts / Oil Pressure',
                'Battery — Charge Level',
                'Gauges & Instruments — Hour Meter / Warning Lights',
                'Boom — Raise / Lower / Extend / Retract',
                'Turret Rotate',
                'Drive — Forward / Reverse',
                'Steer — Right / Left',
                'Platform — Tilt / Rotate',
                'Horn',
                'Outriggers / Stabilizers / Pothole Protection',
                'Extendable Axles',
                'Function-Enable (Deadman) Devices',
                'Manual / Auxiliary Controls',
                'Safety Interlocks']},
 {'id': 'air-compressor',
  'code': 'AC',
  'title': 'Air Compressor',
  'category': 'equipment',
  'folder': '06-Equipment-Inspections/Air-Compressor',
  'icon': '💨',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'inspection_date',
              'label': 'Date of Inspection',
              'type': 'date',
              'required': True,
              'autofill': 'today'},
             {'key': 'inspection_time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'equipment_no', 'label': 'Equipment No.', 'type': 'text', 'required': True},
             {'key': 'equipment_photo',
              'label': 'Inspected Equipment Photo',
              'type': 'photo',
              'required': True},
             {'key': 'inspected_by', 'label': 'Inspected By', 'type': 'inspector', 'required': True}],
  'checklist': ['Condition of overall structure',
                'All bottom control switches in good shape and usable condition',
                'Condition of distribution valve',
                'Engine cover / Rotating shaft has good support',
                'Tow connection in good condition',
                'Battery is covered',
                'Air storage tank in good condition with approved & certified',
                'Any crack or leakage in engine',
                'Safety valve in air system',
                'Base and wheel condition',
                'Pressure gauge condition',
                'Safety valve has test certificate',
                'Condition of pressure relief valve',
                'Earthing on equipment',
                'Condition of starter',
                'Separate earthing on motor',
                'Availability of guard for rotating parts (both sides)',
                'Oil spillage / leakage',
                'Condition of electrical cables',
                'Appropriate cable size is used']},
 {'id': 'arc-welding-machine',
  'code': 'AWM',
  'title': 'Arc Welding Machine',
  'category': 'equipment',
  'folder': '06-Equipment-Inspections/Arc-Welding-Machine',
  'icon': '⚡',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'inspection_date',
              'label': 'Date of Inspection',
              'type': 'date',
              'required': True,
              'autofill': 'today'},
             {'key': 'inspection_time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'equipment_no', 'label': 'Equipment No.', 'type': 'text', 'required': True},
             {'key': 'equipment_photo',
              'label': 'Inspected Equipment Photo',
              'type': 'photo',
              'required': True},
             {'key': 'inspected_by', 'label': 'Inspected By', 'type': 'inspector', 'required': True}],
  'checklist': ['ON / OFF knob is provided (check for damage and uninsulated knob)',
                'Regulator with indicator is provided',
                'Welding cables connected to the welding machine with lugs at the joints',
                'No damage in the insulation of welding cables',
                'Electrode rod holder and earthing holder are without damage',
                'Industrial-type plug for power tapping cable of welding machine',
                'No internal live electrical parts of welding machine are exposed',
                'Trolley without damaged wheels',
                'Fire extinguisher and fire bucket with sand availability',
                'Mandatory signages with inspection tag']},
 {'id': 'cutting-machine',
  'code': 'CM',
  'title': 'Cutting Machine',
  'category': 'equipment',
  'folder': '06-Equipment-Inspections/Cutting-Machine',
  'icon': '✂️',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'inspection_date',
              'label': 'Date of Inspection',
              'type': 'date',
              'required': True,
              'autofill': 'today'},
             {'key': 'inspection_time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'equipment_no', 'label': 'Equipment No.', 'type': 'text', 'required': True},
             {'key': 'equipment_photo',
              'label': 'Inspected Equipment Photo',
              'type': 'photo',
              'required': True},
             {'key': 'inspected_by', 'label': 'Inspected By', 'type': 'inspector', 'required': True}],
  'checklist': ['Crack & damage of the cutting plate',
                'Presence of cutting plate guard',
                'Presence of locking system for the plate & guard',
                'Presence of job clamp and its condition',
                'Presence of handle and its condition',
                'Cable condition (any cut, wear etc.) and presence of wire-top plug',
                'Presence of cutting dust guard']},
 {'id': 'first-aid-box',
  'code': 'FAB',
  'title': 'First Aid Box',
  'category': 'equipment',
  'folder': '06-Equipment-Inspections/First-Aid-Box',
  'icon': '🏥',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'inspection_date',
              'label': 'Date of Inspection',
              'type': 'date',
              'required': True,
              'autofill': 'today'},
             {'key': 'inspection_time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'equipment_no', 'label': 'Equipment No.', 'type': 'text', 'required': True},
             {'key': 'equipment_photo',
              'label': 'Inspected Equipment Photo',
              'type': 'photo',
              'required': True},
             {'key': 'inspected_by', 'label': 'Inspected By', 'type': 'inspector', 'required': True}],
  'checklist': ['Roller bandage 10 cm',
                'Roller bandage 6 cm',
                'Anti-bacterial liquid (Hyd. Peroxide / Dettol / Savlon) 500 ml',
                'Micropore tape (white plaster) 6 cm',
                'Cotton roll big ½ kg',
                'Betadine solution 100 ml',
                'Band-aid (fabric / plastic)',
                'Ointment Soframycin',
                'Ointment Betadine',
                'Scissors (stainless steel) 12 cm',
                'NS bottle (saline)',
                'Ointment Burnovate',
                'Pain-relieving spray / solution (big)',
                'Eye & ear drops (10 ml bottles)',
                'ORS packet']},
 {'id': 'generator',
  'code': 'GEN',
  'title': 'Generator',
  'category': 'equipment',
  'folder': '06-Equipment-Inspections/Generator',
  'icon': '🔋',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'inspection_date',
              'label': 'Date of Inspection',
              'type': 'date',
              'required': True,
              'autofill': 'today'},
             {'key': 'inspection_time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'equipment_no', 'label': 'Equipment No.', 'type': 'text', 'required': True},
             {'key': 'equipment_photo',
              'label': 'Inspected Equipment Photo',
              'type': 'photo',
              'required': True},
             {'key': 'inspected_by', 'label': 'Inspected By', 'type': 'inspector', 'required': True}],
  'checklist': ['Guard provided for any rotating parts',
                'Hot surface is provided with guard',
                'Rubber mat is provided in operator standing area (around the DG)',
                'No oil leakage from the oil tank & other parts of the machine',
                'Wheel stopper in case of vehicle-mounted DG',
                'Proper access to the DG control panel',
                'Exhaust smoke pipe faced upwards & outside of DG shelter',
                'Dip tray for any oil leakage',
                'Drive belt is in good condition (any cut, dent or damage)',
                'Adequate ventilation in case of indoor generator',
                'Presence of fire extinguisher (ABC type)',
                'Damage-free operating switch, voltage and temperature meter, circuit breaker, oil-level '
                'indicator, emergency switch',
                'Earthing is provided with standard earthing pit',
                'In case of mobile gen-set, confirmation of inbuilt acoustic system (if sound is more than '
                '85 dB)']},
 {'id': 'ladder',
  'code': 'LAD',
  'title': 'Ladder',
  'category': 'equipment',
  'folder': '06-Equipment-Inspections/Ladder',
  'icon': '🪜',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'inspection_date',
              'label': 'Date of Inspection',
              'type': 'date',
              'required': True,
              'autofill': 'today'},
             {'key': 'inspection_time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'equipment_no', 'label': 'Equipment No.', 'type': 'text', 'required': True},
             {'key': 'equipment_photo',
              'label': 'Inspected Equipment Photo',
              'type': 'photo',
              'required': True},
             {'key': 'inspected_by', 'label': 'Inspected By', 'type': 'inspector', 'required': True}],
  'checklist': ['All the rungs, cleats, or steps are in good condition (broken, missing, bent rungs)',
                'Side rails are intact without any cracks, bends, or breaks',
                'The rungs, cleats, or steps fit into the side rails without damage',
                'Ladder is free from corrosion',
                'Side rails and steps are free of oil or grease',
                'Rungs are placed at regular intervals (30 cm gap between two rungs)',
                'No projection of loose nails, screws, bolts, or other metal parts',
                'At the time of using, the ladder is placed at 65–75° angle (1:4 ratio)',
                'Ladder extends at least 1 m above the landing platform (3 rungs)',
                'Ladder is secured either at top or bottom',
                'Ladder rungs are not painted',
                'Reinforcement rod is not used as ladder rungs',
                'Surface of the rungs is not smooth',
                'Rubber feet for firm grip (in case of aluminium ladder)']},
 {'id': 'mdb-panel',
  'code': 'MDB',
  'title': 'Main Distribution Board / Panel',
  'category': 'equipment',
  'folder': '06-Equipment-Inspections/Main-Distribution-Board',
  'icon': '🔌',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'inspection_date',
              'label': 'Date of Inspection',
              'type': 'date',
              'required': True,
              'autofill': 'today'},
             {'key': 'inspection_time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'equipment_no', 'label': 'Equipment No.', 'type': 'text', 'required': True},
             {'key': 'equipment_photo',
              'label': 'Inspected Equipment Photo',
              'type': 'photo',
              'required': True},
             {'key': 'inspected_by', 'label': 'Inspected By', 'type': 'inspector', 'required': True}],
  'checklist': ['Firm base with grouting & easily accessible panel (height of the leg ≥ 1 m)',
                'Housing & connections of DB are weather-proof (minimum IP 44 type)',
                'Authorised operator name, photo, contact no. on DB panel (confirmation)',
                'Visualisation of voltage, current and type of tools to be used in the socket & panel',
                'Identification of input and output cables',
                'Confirmation of LOTO availability',
                'Separate MCB for every socket',
                'Safety sign / isolate flammable fire-hazard',
                'Double earthing system of MDB / DB panel with standard earthing pit',
                'Separate ELCB with tripping current of 30 mA & in working condition',
                'Hylem sheet provided over live bus bars',
                'Presence & condition of bus bar / terminal',
                'Condition of cable, power socket and plug without damage',
                'Colour coding (RYB) followed for all cables / wires',
                'Presence of rubber mat in front of the DB (operator standing location)',
                'Plug-socket is industrial type (IP 44 type)']},
 {'id': 'mobile-scaffolding',
  'code': 'MSF',
  'title': 'Mobile Scaffolding',
  'category': 'equipment',
  'folder': '06-Equipment-Inspections/Mobile-Scaffolding',
  'icon': '🪟',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'inspection_date',
              'label': 'Date of Inspection',
              'type': 'date',
              'required': True,
              'autofill': 'today'},
             {'key': 'inspection_time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'equipment_no', 'label': 'Equipment No.', 'type': 'text', 'required': True},
             {'key': 'equipment_photo',
              'label': 'Inspected Equipment Photo',
              'type': 'photo',
              'required': True},
             {'key': 'inspected_by', 'label': 'Inspected By', 'type': 'inspector', 'required': True}],
  'checklist': ['Inspect structure of scaffolding daily before use',
                'Worker must be trained for working at height before using scaffolding',
                'Use full body harness with shock-absorbing lanyard',
                'No unauthorised modification in scaffolding',
                'Do not store equipment or material on platform of scaffolding',
                'Do not allow worker to stay on scaffolding when moving scaffolding',
                'Do not allow worker to stay in front of scaffolding when moving scaffolding',
                'Tools and equipment used on scaffolding must be tied with rope',
                'Lock all wheels before working on scaffolding',
                'Barricade working area',
                'Do not carry heavy weight when walking on ladder of scaffolding',
                'Do not stand on handrail or climb out of scaffolding',
                'Housekeeping of working area after finishing work daily',
                'Scaffolding load test certificate available']},
 {'id': 'scaffolding-cuplock',
  'code': 'SCL',
  'title': 'Scaffolding (Cuplock)',
  'category': 'equipment',
  'folder': '06-Equipment-Inspections/Scaffolding-Cuplock',
  'icon': '🏗️',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'inspection_date',
              'label': 'Date of Inspection',
              'type': 'date',
              'required': True,
              'autofill': 'today'},
             {'key': 'inspection_time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'equipment_no', 'label': 'Equipment No.', 'type': 'text', 'required': True},
             {'key': 'equipment_photo',
              'label': 'Inspected Equipment Photo',
              'type': 'photo',
              'required': True},
             {'key': 'inspected_by', 'label': 'Inspected By', 'type': 'inspector', 'required': True}],
  'checklist': ['Display board stating the status of the scaffold (OK / Not for use / Under erection)',
                'Scaffold erected on a firm base ground',
                'Sole plate provided in the base of the scaffold as per standard (full-length wooden planks '
                '/ channels)',
                'Base plate / foot plate of scaffold verticals are over the wooden planks (sole plate)',
                'Cup lock locking is not in loose condition',
                'Access ladder from the ground & each lift, secured with clamps',
                'Ladder kept in channels over the jallies in the first lift and above',
                'Each lift provided with platform (jallies) tied with horizontal pipes',
                'All four-side support pipes (struts) properly clamped',
                'Interlocking between the columns & scaffold in case of more than 6 m height scaffolds',
                'All lifts in the scaffold provided with mid-rails (hand-rails)']},
 {'id': 'truck',
  'code': 'TRK',
  'title': 'Truck',
  'category': 'equipment',
  'folder': '06-Equipment-Inspections/Truck',
  'icon': '🚚',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'inspection_date',
              'label': 'Date of Inspection',
              'type': 'date',
              'required': True,
              'autofill': 'today'},
             {'key': 'inspection_time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'equipment_no', 'label': 'Equipment No.', 'type': 'text', 'required': True},
             {'key': 'equipment_photo',
              'label': 'Inspected Equipment Photo',
              'type': 'photo',
              'required': True},
             {'key': 'inspected_by', 'label': 'Inspected By', 'type': 'inspector', 'required': True}],
  'checklist': ['Number plate in front and back side',
                'No damage in tyre (crack, cut, air pressure etc.)',
                'No air leak in the air tank',
                'Front and reverse horn',
                'No oil leak from the diesel tank',
                'Fire extinguisher in driver cabin',
                'Head and tail lamps (for night working)',
                'Brake, clutch and accelerator are in working condition',
                'Truck is not overloaded',
                'Rear-view mirror',
                'Wind shield with wiper',
                'Vehicle valid insurance',
                'Operator licence (heavy duty)',
                'Road tax']},
 {'id': 'labour-camp',
  'code': 'LC',
  'title': 'Labour Camp',
  'category': 'equipment',
  'folder': '06-Equipment-Inspections/Labour-Camp',
  'icon': '🏠',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'inspection_date',
              'label': 'Date of Inspection',
              'type': 'date',
              'required': True,
              'autofill': 'today'},
             {'key': 'inspection_time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'equipment_no', 'label': 'Equipment No.', 'type': 'text', 'required': True},
             {'key': 'equipment_photo',
              'label': 'Inspected Equipment Photo',
              'type': 'photo',
              'required': True},
             {'key': 'inspected_by', 'label': 'Inspected By', 'type': 'inspector', 'required': True}],
  'checklist': ['Toilets condition',
                'Dressing of electrical cables',
                'Labour cooking area (safe / not)',
                'Housekeeping',
                'Availability of first-aid box with safe custody',
                'Availability of fire extinguisher',
                'Availability of security',
                'Condition of drainage system',
                'Availability of drinking water',
                'Any unauthorised persons staying at camp?']},
 {'id': 'mobile-crane',
  'code': 'MC',
  'title': 'Mobile Crane',
  'category': 'equipment',
  'folder': '06-Equipment-Inspections/Mobile-Crane',
  'icon': '🏗️',
  'fields': [{'key': 'project_name', 'label': 'Project Name', 'type': 'project', 'required': True},
             {'key': 'inspection_date',
              'label': 'Date of Inspection',
              'type': 'date',
              'required': True,
              'autofill': 'today'},
             {'key': 'inspection_time', 'label': 'Time', 'type': 'time', 'required': True, 'autofill': 'now'},
             {'key': 'equipment_no', 'label': 'Equipment No.', 'type': 'text', 'required': True},
             {'key': 'equipment_photo',
              'label': 'Inspected Equipment Photo',
              'type': 'photo',
              'required': True},
             {'key': 'inspected_by', 'label': 'Inspected By', 'type': 'inspector', 'required': True}],
  'checklist': ['Safety latch in hook',
                'Hoist limit switch (or presence of plate)',
                'SWL marked on crane',
                'Wire rope and slings free from tolerable damage (no kinks; broken wires more than 10% is '
                'N.G.)',
                'No oil leak in hydraulic parts (piston drums)',
                'No damage in tyre (crack, cut, air pressure etc.)',
                'Head and tail lamps (for night working)',
                'Front and reverse horn',
                'Boom structure condition while full expansion (damage, crack and jamming while extending)',
                'Fire extinguisher in operator cabin',
                'Operator licence (heavy duty)',
                'Third-party certificate (Form 32)',
                'Vehicle valid insurance']}]

FORMS_BY_ID = {f["id"]: f for f in ALL_FORMS}

GENERAL_FORMS = [f for f in ALL_FORMS if f["category"] == "general"]
EQUIPMENT_FORMS = [f for f in ALL_FORMS if f["category"] == "equipment"]


def get_approver_emails() -> list[str]:
    """Approver emails, overridable via env."""
    import os

    raw = os.getenv("EHS_APPROVER_EMAILS", "")
    if raw.strip():
        return [e.strip().lower() for e in raw.split(",") if e.strip()]
    return [e.lower() for e in APPROVER_EMAILS]


def is_approver(user) -> bool:
    """Admins and configured approver emails can approve/reject."""
    if getattr(user, "is_admin", False):
        return True
    email = (getattr(user, "email", "") or "").lower()
    return email in get_approver_emails()

