"""Seed data: 20 KPI-tracked employees + 2 admin-only accounts.

Note: emails are NOT unique. One email can host multiple employees
(currently `admin@metfraa.com` is shared by Sheela + Sudha).
"""
from datetime import date

ADMIN_EMAILS = {
    "info@metfraa.com",
    "arasu@metfraa.com",
    "nirmal@metfraa.com",
}

EMPLOYEES_SEED = [
    # ============================================================
    # ORIGINAL 8 EMPLOYEES (KPIs already approved by user)
    # ============================================================
    {
        "email": "nirmal@metfraa.com",
        "name": "Nirmal Kumar",
        "designation": "AGM",
        "department": "Multi-Departmental Operations",
        "reports_to": "Managing Director",
        "date_of_joining": date(2026, 2, 13),
        "is_admin": True,
        "kpis": [
            {"name": "Cross-functional review meetings chaired", "unit": "Count", "weight": 12, "target": 22},
            {"name": "Department KPIs reviewed", "unit": "Count", "weight": 12, "target": 60},
            {"name": "Project escalations resolved", "unit": "Count", "weight": 12, "target": 20},
            {"name": "Site / Plant visits conducted", "unit": "Count", "weight": 8, "target": 8},
            {"name": "POs / Vendor approvals signed off", "unit": "Count", "weight": 10, "target": 40},
            {"name": "NCRs / CAPAs reviewed & closed", "unit": "Count", "weight": 10, "target": 30},
            {"name": "Drawings / Designs reviewed & approved", "unit": "Count", "weight": 10, "target": 50},
            {"name": "Safety walks / EHS reviews conducted", "unit": "Count", "weight": 8, "target": 12},
            {"name": "Client interactions / meetings", "unit": "Count", "weight": 8, "target": 15},
            {"name": "MIS reports reviewed & signed off", "unit": "Count", "weight": 10, "target": 20},
        ],
    },
    {
        "email": "khajasheriff.m@metfraa.com",
        "name": "Khaja Sheriff",
        "designation": "GM Design",
        "department": "Design & Engineering",
        "reports_to": "AGM",
        "date_of_joining": date(2025, 4, 4),
        "is_admin": False,
        "kpis": [
            {"name": "Structural calculations reviewed / approved", "unit": "Count", "weight": 12, "target": 40},
            {"name": "GA / Fabrication / Erection drawings approved", "unit": "Count", "weight": 15, "target": 80},
            {"name": "Drawings released as per schedule (DSA)", "unit": "Count", "weight": 12, "target": 60},
            {"name": "RFIs closed", "unit": "Count", "weight": 10, "target": 30},
            {"name": "Design change requests processed", "unit": "Count", "weight": 8, "target": 15},
            {"name": "Client technical meetings / approvals", "unit": "Count", "weight": 10, "target": 15},
            {"name": "Design NCRs reviewed & resolved", "unit": "Count", "weight": 8, "target": 10},
            {"name": "Peer reviews / Drawing checks done", "unit": "Count", "weight": 10, "target": 50},
            {"name": "Team coaching / training sessions", "unit": "Count", "weight": 5, "target": 4},
            {"name": "BIM / Tekla model coordination tasks", "unit": "Count", "weight": 10, "target": 30},
        ],
    },
    {
        "email": "purchase@metfraa.com",
        "name": "Suresh Kumar",
        "designation": "GM Purchase",
        "department": "Purchase & Supply Chain",
        "reports_to": "AGM",
        "date_of_joining": date(2025, 9, 11),
        "is_admin": False,
        "kpis": [
            {"name": "POs raised in ERP", "unit": "Count", "weight": 12, "target": 60},
            {"name": "POs approved (within authority matrix)", "unit": "Count", "weight": 10, "target": 50},
            {"name": "Indents processed (received → action)", "unit": "Count", "weight": 10, "target": 80},
            {"name": "GRNs verified / cleared", "unit": "Count", "weight": 10, "target": 80},
            {"name": "Vendor negotiations / quote comparisons", "unit": "Count", "weight": 10, "target": 30},
            {"name": "New vendors registered / qualified", "unit": "Count", "weight": 8, "target": 5},
            {"name": "Material rejections handled (RTV)", "unit": "Count", "weight": 8, "target": 8},
            {"name": "Cost-saving entries logged", "unit": "Count", "weight": 12, "target": 15},
            {"name": "Stock / Inventory reviews", "unit": "Count", "weight": 10, "target": 12},
            {"name": "Subcontractor / Logistics coordination", "unit": "Count", "weight": 10, "target": 25},
        ],
    },
    {
        "email": "sathya@metfraa.com",
        "name": "Sathiyaseelan",
        "designation": "GM Sales",
        "department": "Sales & Business Development",
        "reports_to": "Managing Director",
        "date_of_joining": date(2025, 9, 15),
        "is_admin": False,
        "kpis": [
            {"name": "New leads generated", "unit": "Count", "weight": 12, "target": 40},
            {"name": "Client meetings / calls held", "unit": "Count", "weight": 12, "target": 50},
            {"name": "Proposals / Quotations submitted", "unit": "Count", "weight": 15, "target": 20},
            {"name": "RFQs reviewed", "unit": "Count", "weight": 8, "target": 30},
            {"name": "Negotiations / Order closures", "unit": "Count", "weight": 15, "target": 8},
            {"name": "Pipeline updates in CRM", "unit": "Count", "weight": 8, "target": 80},
            {"name": "Site visits / Client demos", "unit": "Count", "weight": 8, "target": 8},
            {"name": "Channel partner / Dealer interactions", "unit": "Count", "weight": 7, "target": 10},
            {"name": "Receivables / Payment follow-ups", "unit": "Count", "weight": 10, "target": 25},
            {"name": "Competitor / Market intelligence updates", "unit": "Count", "weight": 5, "target": 4},
        ],
    },
    {
        "email": "thangaraj@metfraa.com",
        "name": "Thangaraj",
        "designation": "Plant Head",
        "department": "Production & Fabrication",
        "reports_to": "AGM",
        "date_of_joining": date(2025, 10, 3),
        "is_admin": False,
        "kpis": [
            {"name": "Tonnage produced", "unit": "MT", "weight": 15, "target": 500},
            {"name": "Daily production review meetings", "unit": "Count", "weight": 8, "target": 22},
            {"name": "Components passed at first inspection (FTR)", "unit": "Count", "weight": 12, "target": 200},
            {"name": "NCRs raised / closed", "unit": "Count", "weight": 10, "target": 12},
            {"name": "Equipment breakdowns handled", "unit": "Count", "weight": 8, "target": 8},
            {"name": "Welding / Surface QC checks done", "unit": "Count", "weight": 10, "target": 60},
            {"name": "Material indents raised", "unit": "Count", "weight": 8, "target": 25},
            {"name": "Dispatch lots cleared", "unit": "Count", "weight": 12, "target": 20},
            {"name": "Safety walks / Toolbox talks conducted", "unit": "Count", "weight": 10, "target": 22},
            {"name": "Manpower deployment & attendance reviewed", "unit": "Count", "weight": 7, "target": 22},
        ],
    },
    {
        "email": "varadharaj@metfraa.com",
        "name": "Vardharaj Navaneethan",
        "designation": "Asst. Manager EHS",
        "department": "Environment, Health & Safety",
        "reports_to": "AGM",
        "date_of_joining": date(2026, 4, 10),
        "is_admin": False,
        "kpis": [
            {"name": "Safety walks / Inspections conducted", "unit": "Count", "weight": 12, "target": 22},
            {"name": "Toolbox talks delivered", "unit": "Count", "weight": 10, "target": 8},
            {"name": "Work permits issued / monitored", "unit": "Count", "weight": 10, "target": 30},
            {"name": "Near-misses / Incidents reported", "unit": "Count", "weight": 12, "target": 5},
            {"name": "Incident investigations completed", "unit": "Count", "weight": 10, "target": 3},
            {"name": "CAPAs tracked & closed", "unit": "Count", "weight": 10, "target": 8},
            {"name": "EHS inductions conducted", "unit": "Count", "weight": 8, "target": 10},
            {"name": "NCRs raised on safety violations", "unit": "Count", "weight": 8, "target": 10},
            {"name": "Statutory compliance checks done", "unit": "Count", "weight": 10, "target": 6},
            {"name": "Emergency drills / PPE checks conducted", "unit": "Count", "weight": 10, "target": 4},
        ],
    },
    {
        "email": "m.gopi@metfraa.com",
        "name": "Gopi Mahendiran M",
        "designation": "Detailer",
        "department": "Engineering & Detailing",
        "reports_to": "GM Design",
        "date_of_joining": date(2026, 4, 20),
        "is_admin": False,
        "kpis": [
            {"name": "Shop drawings produced", "unit": "Count", "weight": 15, "target": 60},
            {"name": "GA / Erection drawings produced", "unit": "Count", "weight": 12, "target": 30},
            {"name": "Tonnage detailed", "unit": "MT", "weight": 12, "target": 200},
            {"name": "BOQs / MTOs prepared", "unit": "Count", "weight": 10, "target": 12},
            {"name": "Design estimates issued (pre-sales)", "unit": "Count", "weight": 10, "target": 15},
            {"name": "Drawings revised (rework)", "unit": "Count", "weight": 8, "target": 15},
            {"name": "Concept / Tender drawings prepared", "unit": "Count", "weight": 8, "target": 10},
            {"name": "RFIs / Site queries resolved", "unit": "Count", "weight": 8, "target": 20},
            {"name": "ERP updates done (same day)", "unit": "Count", "weight": 10, "target": 22},
            {"name": "Library / Standardisation entries added", "unit": "Count", "weight": 7, "target": 10},
        ],
    },
    {
        "email": "mansoor@metfraa.com",
        "name": "Mansoor",
        "designation": "Senior Checker",
        "department": "Engineering & Design",
        "reports_to": "GM Design",
        "date_of_joining": date(2026, 4, 25),
        "is_admin": False,
        "kpis": [
            {"name": "Drawings checked & cleared for release", "unit": "Count", "weight": 18, "target": 80},
            {"name": "Drawings returned with comments", "unit": "Count", "weight": 10, "target": 30},
            {"name": "Major comments raised", "unit": "Count", "weight": 10, "target": 15},
            {"name": "Minor comments raised", "unit": "Count", "weight": 8, "target": 40},
            {"name": "BOM variances flagged", "unit": "Count", "weight": 10, "target": 8},
            {"name": "Code / Standards compliance checks done", "unit": "Count", "weight": 10, "target": 50},
            {"name": "Comments closed (re-verified)", "unit": "Count", "weight": 12, "target": 60},
            {"name": "Anchor bolt / GA drawings checked", "unit": "Count", "weight": 8, "target": 25},
            {"name": "Check register entries logged (same day)", "unit": "Count", "weight": 8, "target": 22},
            {"name": "Detailer feedback sessions held", "unit": "Count", "weight": 6, "target": 4},
        ],
    },

    # ============================================================
    # 12 NEW EMPLOYEES (from new JRRs)
    # ============================================================
    {
        "email": "gopi@metfraa.com",
        "name": "Gopi",
        "designation": "Production Manager",
        "department": "Production & Fabrication",
        "reports_to": "Plant Head",
        "is_admin": False,
        "kpis": [
            {"name": "Tonnes fabricated (vs plan)", "unit": "MT", "weight": 14, "target": 500},
            {"name": "Jobs completed on / before schedule", "unit": "Count", "weight": 12, "target": 22},
            {"name": "Productive machine hours logged", "unit": "Hours", "weight": 8, "target": 1700},
            {"name": "Rework / rejected tonnage", "unit": "MT", "weight": 10, "target": 10},
            {"name": "Material wastage entries (scrap log)", "unit": "Count", "weight": 8, "target": 22},
            {"name": "Daily production planning meetings", "unit": "Count", "weight": 6, "target": 22},
            {"name": "Overtime hours logged", "unit": "Hours", "weight": 6, "target": 200},
            {"name": "Preventive maintenance tasks completed", "unit": "Count", "weight": 8, "target": 15},
            {"name": "Breakdown incidents resolved", "unit": "Count", "weight": 8, "target": 10},
            {"name": "Dispatch lots released to site", "unit": "Count", "weight": 10, "target": 20},
            {"name": "Safety / 5S walks conducted", "unit": "Count", "weight": 6, "target": 12},
            {"name": "Operator training / cross-skill sessions", "unit": "Count", "weight": 4, "target": 2},
        ],
    },
    {
        "email": "qaqc@metfraa.com",
        "name": "Suresh",
        "designation": "Quality Engineer",
        "department": "Quality Control",
        "reports_to": "Plant Head",
        "is_admin": False,
        "kpis": [
            {"name": "Incoming material inspections", "unit": "Count", "weight": 12, "target": 40},
            {"name": "NCRs raised", "unit": "Count", "weight": 10, "target": 15},
            {"name": "NCRs closed (within target)", "unit": "Count", "weight": 12, "target": 12},
            {"name": "Weld inspections conducted", "unit": "Count", "weight": 10, "target": 100},
            {"name": "Dimensional checks performed", "unit": "Count", "weight": 8, "target": 80},
            {"name": "Surface treatment / DFT verifications", "unit": "Count", "weight": 8, "target": 22},
            {"name": "ITP hold-points signed (Plant)", "unit": "Count", "weight": 10, "target": 60},
            {"name": "ITP hold-points signed (Site)", "unit": "Count", "weight": 8, "target": 30},
            {"name": "Site erection QC checklists completed", "unit": "Count", "weight": 8, "target": 15},
            {"name": "QC documentation entries (same day)", "unit": "Count", "weight": 8, "target": 22},
            {"name": "WPS / WQT compliance audits", "unit": "Count", "weight": 6, "target": 4},
        ],
    },
    {
        "email": "vijay@metfraa.com",
        "name": "Vijay",
        "designation": "Project Manager - Civil",
        "department": "Projects (Civil)",
        "reports_to": "AGM Projects",
        "is_admin": False,
        "kpis": [
            {"name": "Civil milestones completed (vs plan)", "unit": "Count", "weight": 12, "target": 12},
            {"name": "Foundations / anchor bolts handed over", "unit": "Count", "weight": 12, "target": 8},
            {"name": "Concrete cube tests passed", "unit": "Count", "weight": 10, "target": 30},
            {"name": "Compaction tests recorded", "unit": "Count", "weight": 8, "target": 20},
            {"name": "Civil NCRs raised", "unit": "Count", "weight": 8, "target": 8},
            {"name": "Civil NCRs closed", "unit": "Count", "weight": 8, "target": 8},
            {"name": "Sub-contractor bills certified", "unit": "Count", "weight": 8, "target": 12},
            {"name": "MTC verifications recorded", "unit": "Count", "weight": 8, "target": 25},
            {"name": "ITP hold-points signed", "unit": "Count", "weight": 10, "target": 30},
            {"name": "Site visits / inspections done", "unit": "Count", "weight": 8, "target": 20},
            {"name": "Safety walks / PPE audits", "unit": "Count", "weight": 8, "target": 12},
        ],
    },
    {
        "email": "nainar@metfraa.com",
        "name": "Nainar",
        "designation": "Project Manager",
        "department": "Projects (PEB)",
        "reports_to": "AGM Projects",
        "date_of_joining": date(2026, 1, 5),
        "is_admin": False,
        "kpis": [
            {"name": "Project milestones achieved", "unit": "Count", "weight": 12, "target": 10},
            {"name": "Drawing approvals secured from client", "unit": "Count", "weight": 10, "target": 12},
            {"name": "Variation / change orders submitted", "unit": "Count", "weight": 8, "target": 6},
            {"name": "Client billing milestones invoiced", "unit": "Count", "weight": 12, "target": 8},
            {"name": "Payment collection follow-ups", "unit": "Count", "weight": 10, "target": 15},
            {"name": "Fabrication dispatches coordinated", "unit": "Count", "weight": 10, "target": 12},
            {"name": "Site progress reviews conducted", "unit": "Count", "weight": 10, "target": 15},
            {"name": "Snag list items closed", "unit": "Count", "weight": 8, "target": 30},
            {"name": "QC / NCR coordination instances", "unit": "Count", "weight": 8, "target": 10},
            {"name": "Safety / EHS audits done", "unit": "Count", "weight": 6, "target": 8},
            {"name": "Client meetings held", "unit": "Count", "weight": 6, "target": 10},
        ],
    },
    {
        "email": "raja@metfraa.com",
        "name": "Rajakumaran",
        "designation": "Project Manager",
        "department": "Projects (PEB)",
        "reports_to": "AGM Projects",
        "date_of_joining": date(2026, 3, 9),
        "is_admin": False,
        "kpis": [
            {"name": "Project milestones achieved", "unit": "Count", "weight": 12, "target": 10},
            {"name": "Drawing approvals secured from client", "unit": "Count", "weight": 10, "target": 12},
            {"name": "Variation / change orders submitted", "unit": "Count", "weight": 8, "target": 6},
            {"name": "Client billing milestones invoiced", "unit": "Count", "weight": 12, "target": 8},
            {"name": "Payment collection follow-ups", "unit": "Count", "weight": 10, "target": 15},
            {"name": "Fabrication dispatches coordinated", "unit": "Count", "weight": 10, "target": 12},
            {"name": "Site progress reviews conducted", "unit": "Count", "weight": 10, "target": 15},
            {"name": "Snag list items closed", "unit": "Count", "weight": 8, "target": 30},
            {"name": "QC / NCR coordination instances", "unit": "Count", "weight": 8, "target": 10},
            {"name": "Safety / EHS audits done", "unit": "Count", "weight": 6, "target": 8},
            {"name": "Client meetings held", "unit": "Count", "weight": 6, "target": 10},
        ],
    },
    {
        "email": "thanavel@metfraa.com",
        "name": "Thanavel",
        "designation": "Project Manager",
        "department": "Projects (PEB)",
        "reports_to": "AGM Projects",
        "date_of_joining": date(2025, 2, 3),
        "is_admin": False,
        "kpis": [
            {"name": "Project milestones achieved", "unit": "Count", "weight": 12, "target": 10},
            {"name": "Drawing approvals secured from client", "unit": "Count", "weight": 10, "target": 12},
            {"name": "Variation / change orders submitted", "unit": "Count", "weight": 8, "target": 6},
            {"name": "Client billing milestones invoiced", "unit": "Count", "weight": 12, "target": 8},
            {"name": "Payment collection follow-ups", "unit": "Count", "weight": 10, "target": 15},
            {"name": "Fabrication dispatches coordinated", "unit": "Count", "weight": 10, "target": 12},
            {"name": "Site progress reviews conducted", "unit": "Count", "weight": 10, "target": 15},
            {"name": "Snag list items closed", "unit": "Count", "weight": 8, "target": 30},
            {"name": "QC / NCR coordination instances", "unit": "Count", "weight": 8, "target": 10},
            {"name": "Safety / EHS audits done", "unit": "Count", "weight": 6, "target": 8},
            {"name": "Client meetings held", "unit": "Count", "weight": 6, "target": 10},
        ],
    },
    {
        "email": "sumana@metfraa.com",
        "name": "Sumana",
        "designation": "Project Coordinator",
        "department": "Projects (PEB)",
        "reports_to": "Project Manager",
        "is_admin": False,
        "kpis": [
            {"name": "Drawing submittals sent to customer", "unit": "Count", "weight": 10, "target": 15},
            {"name": "Customer drawing approvals followed up", "unit": "Count", "weight": 8, "target": 15},
            {"name": "Dispatch advice notes issued", "unit": "Count", "weight": 10, "target": 18},
            {"name": "Site material receipt confirmations logged", "unit": "Count", "weight": 8, "target": 18},
            {"name": "Site issue resolutions tracked", "unit": "Count", "weight": 8, "target": 12},
            {"name": "Customer communications responded", "unit": "Count", "weight": 8, "target": 30},
            {"name": "Variation register updates", "unit": "Count", "weight": 8, "target": 8},
            {"name": "Invoices submitted to client", "unit": "Count", "weight": 10, "target": 8},
            {"name": "Payment follow-up calls / mails", "unit": "Count", "weight": 8, "target": 15},
            {"name": "NCRs / punch list items closed", "unit": "Count", "weight": 8, "target": 15},
            {"name": "Project documents filed in DMS", "unit": "Count", "weight": 8, "target": 60},
            {"name": "MoM / meeting summaries issued", "unit": "Count", "weight": 6, "target": 8},
        ],
    },
    {
        "email": "saraneeswari@metfraa.com",
        "name": "C. Saraneeswari",
        "designation": "Senior Design Engineer",
        "department": "Design & Engineering",
        "reports_to": "GM Design",
        "is_admin": False,
        "kpis": [
            {"name": "Drawings issued (on-time)", "unit": "Count", "weight": 12, "target": 30},
            {"name": "Internal Design Reviews completed", "unit": "Count", "weight": 10, "target": 4},
            {"name": "Design calculations released", "unit": "Count", "weight": 12, "target": 20},
            {"name": "RFIs responded", "unit": "Count", "weight": 10, "target": 25},
            {"name": "Technical submittals to client", "unit": "Count", "weight": 10, "target": 12},
            {"name": "MTOs prepared / verified", "unit": "Count", "weight": 8, "target": 8},
            {"name": "Junior team outputs reviewed", "unit": "Count", "weight": 10, "target": 25},
            {"name": "Drawing revisions issued", "unit": "Count", "weight": 8, "target": 15},
            {"name": "Drawing register updates (DMS)", "unit": "Count", "weight": 8, "target": 30},
            {"name": "Design rework hours logged", "unit": "Hours", "weight": 6, "target": 30},
            {"name": "Coordination meetings (cross-team)", "unit": "Count", "weight": 6, "target": 8},
        ],
    },
    {
        "email": "costing@metfraa.com",
        "name": "Salma",
        "designation": "Costing & Estimation Engineer",
        "department": "Estimation & Commercial",
        "reports_to": "Head of Estimation",
        "is_admin": False,
        "kpis": [
            {"name": "Bids submitted", "unit": "Count", "weight": 12, "target": 12},
            {"name": "Bids submitted on-time", "unit": "Count", "weight": 12, "target": 12},
            {"name": "Enquiries logged in register", "unit": "Count", "weight": 10, "target": 15},
            {"name": "Enquiries converted to bids", "unit": "Count", "weight": 10, "target": 12},
            {"name": "Bids won (orders / LOIs)", "unit": "Count", "weight": 12, "target": 3},
            {"name": "Rate database updates", "unit": "Count", "weight": 8, "target": 4},
            {"name": "Steel market alerts issued", "unit": "Count", "weight": 6, "target": 4},
            {"name": "Value engineering proposals submitted", "unit": "Count", "weight": 10, "target": 2},
            {"name": "BCP sheets prepared (post-order)", "unit": "Count", "weight": 8, "target": 3},
            {"name": "Variance reports filed", "unit": "Count", "weight": 6, "target": 3},
            {"name": "Bid file completeness reviews", "unit": "Count", "weight": 6, "target": 12},
        ],
    },
    {
        "email": "accounts@metfraa.com",
        "name": "Sathya",
        "designation": "Accounts Assistant",
        "department": "Finance & Accounts",
        "reports_to": "Finance Manager",
        "is_admin": False,
        "kpis": [
            {"name": "Invoices processed (within 2 WD)", "unit": "Count", "weight": 12, "target": 80},
            {"name": "Bank entries / reconciliations", "unit": "Count", "weight": 10, "target": 22},
            {"name": "TDS / GST entries posted", "unit": "Count", "weight": 10, "target": 30},
            {"name": "Payment proposals prepared", "unit": "Count", "weight": 10, "target": 20},
            {"name": "GRN / PO matching done", "unit": "Count", "weight": 10, "target": 60},
            {"name": "Subcontractor bills certified & posted", "unit": "Count", "weight": 8, "target": 15},
            {"name": "Project cost entries booked (Tally)", "unit": "Count", "weight": 10, "target": 60},
            {"name": "AR collection follow-ups", "unit": "Count", "weight": 8, "target": 25},
            {"name": "Payroll inputs verified", "unit": "Count", "weight": 8, "target": 8},
            {"name": "Audit queries responded", "unit": "Count", "weight": 6, "target": 8},
            {"name": "Documents filed / archived (same day)", "unit": "Count", "weight": 8, "target": 60},
        ],
    },
    {
        "email": "admin@metfraa.com",
        "name": "Sheela Hepsibah Grace",
        "designation": "HR Assistant",
        "department": "Human Resources",
        "reports_to": "HR Manager",
        "is_admin": False,
        "kpis": [
            {"name": "Keka profile updates / new joiners onboarded", "unit": "Count", "weight": 10, "target": 5},
            {"name": "Attendance entries verified in Keka", "unit": "Count", "weight": 12, "target": 22},
            {"name": "Leave records updated (within 24 hr)", "unit": "Count", "weight": 10, "target": 25},
            {"name": "HR letters drafted", "unit": "Count", "weight": 8, "target": 8},
            {"name": "Employee files audited / updated", "unit": "Count", "weight": 10, "target": 20},
            {"name": "Payroll inputs reviewed / submitted", "unit": "Count", "weight": 10, "target": 22},
            {"name": "Pay register entries reviewed", "unit": "Count", "weight": 8, "target": 50},
            {"name": "Exit formalities processed", "unit": "Count", "weight": 8, "target": 2},
            {"name": "HR queries / requests resolved", "unit": "Count", "weight": 10, "target": 30},
            {"name": "Compliance documents filed", "unit": "Count", "weight": 8, "target": 8},
            {"name": "MIS / HR reports submitted", "unit": "Count", "weight": 6, "target": 4},
        ],
    },
    {
        "email": "admin@metfraa.com",  # SHARED with Sheela
        "name": "Sudha",
        "designation": "Admin Executive",
        "department": "Administration",
        "reports_to": "HR Manager",
        "is_admin": False,
        "kpis": [
            {"name": "Daily task reports collected from team", "unit": "Count", "weight": 10, "target": 22},
            {"name": "Site attendance logs updated", "unit": "Count", "weight": 10, "target": 22},
            {"name": "Visitor / gate pass logs", "unit": "Count", "weight": 8, "target": 25},
            {"name": "Travel / accommodation bookings", "unit": "Count", "weight": 8, "target": 12},
            {"name": "Stationery / supply requests handled", "unit": "Count", "weight": 6, "target": 15},
            {"name": "Admin invoices processed", "unit": "Count", "weight": 8, "target": 15},
            {"name": "Facility / AMC visits coordinated", "unit": "Count", "weight": 8, "target": 6},
            {"name": "Documents filed / scanned", "unit": "Count", "weight": 10, "target": 60},
            {"name": "Joining / exit support tasks", "unit": "Count", "weight": 8, "target": 6},
            {"name": "Courier / dispatch tasks handled", "unit": "Count", "weight": 8, "target": 25},
            {"name": "Meetings / events coordinated", "unit": "Count", "weight": 8, "target": 8},
            {"name": "Vehicle / logistics requests fulfilled", "unit": "Count", "weight": 8, "target": 15},
        ],
    },

    # ============================================================
    # 6 NEW EMPLOYEES (Round 3 - Maintenance, Production, Site, Stores)
    # Some on personal emails (added as Azure Guest users)
    # ============================================================
    {
        "email": "maintenance@metfraa.com",
        "name": "Ajoy Kumar Khatua",
        "designation": "Asst. Manager Maintenance",
        "department": "Maintenance & Utilities",
        "reports_to": "Plant Head",
        "is_admin": False,
        "kpis": [
            {"name": "PM tasks completed (vs plan)", "unit": "Count", "weight": 12, "target": 25},
            {"name": "Breakdown response calls handled", "unit": "Count", "weight": 10, "target": 12},
            {"name": "Critical equipment uptime checks done", "unit": "Count", "weight": 10, "target": 22},
            {"name": "Thermographic / panel inspections", "unit": "Count", "weight": 8, "target": 6},
            {"name": "Lifting equipment certifications verified", "unit": "Count", "weight": 8, "target": 8},
            {"name": "Statutory inspections completed", "unit": "Count", "weight": 10, "target": 6},
            {"name": "LOTO / Permit-to-Work approvals", "unit": "Count", "weight": 10, "target": 18},
            {"name": "IMTE calibrations verified", "unit": "Count", "weight": 8, "target": 12},
            {"name": "Spare parts indents raised", "unit": "Count", "weight": 8, "target": 15},
            {"name": "CAI (corrective action items) closed", "unit": "Count", "weight": 8, "target": 10},
            {"name": "Maintenance safety walks", "unit": "Count", "weight": 8, "target": 12},
        ],
    },
    {
        "email": "rajsathosh1@gmail.com",
        "name": "Santhosh Raj",
        "designation": "Production Engineer",
        "department": "Production & Fabrication",
        "reports_to": "Production Manager",
        "is_admin": False,
        "kpis": [
            {"name": "Tonnage produced (vs plan)", "unit": "MT", "weight": 14, "target": 250},
            {"name": "Jobs dispatched on-time", "unit": "Count", "weight": 12, "target": 20},
            {"name": "Drawing-to-production handovers", "unit": "Count", "weight": 8, "target": 22},
            {"name": "CNC plasma run hours logged", "unit": "Hours", "weight": 8, "target": 180},
            {"name": "SAW / welding run hours logged", "unit": "Hours", "weight": 8, "target": 160},
            {"name": "Shot blast / paint run hours", "unit": "Hours", "weight": 6, "target": 140},
            {"name": "Components passing first inspection (FTAR)", "unit": "Count", "weight": 10, "target": 200},
            {"name": "Rework cases handled", "unit": "Count", "weight": 8, "target": 10},
            {"name": "NCRs closed", "unit": "Count", "weight": 8, "target": 12},
            {"name": "5S / safety walks done", "unit": "Count", "weight": 8, "target": 12},
            {"name": "ERP entries posted same-day", "unit": "Count", "weight": 6, "target": 22},
            {"name": "Manpower attendance reviews", "unit": "Count", "weight": 4, "target": 22},
        ],
    },
    {
        "email": "stores@metfraa.com",
        "name": "Deena Dhayalan Ramesh",
        "designation": "Store Executive",
        "department": "Stores & Inventory",
        "reports_to": "Plant Head",
        "is_admin": False,
        "kpis": [
            {"name": "GRNs booked same-day", "unit": "Count", "weight": 12, "target": 22},
            {"name": "Inward QC inspections cleared", "unit": "Count", "weight": 10, "target": 30},
            {"name": "Material issues processed", "unit": "Count", "weight": 12, "target": 60},
            {"name": "Cycle counts performed", "unit": "Count", "weight": 8, "target": 22},
            {"name": "Stock variances reconciled", "unit": "Count", "weight": 8, "target": 10},
            {"name": "Dispatches released to site (OTIF)", "unit": "Count", "weight": 10, "target": 15},
            {"name": "Stock-out incidents prevented", "unit": "Count", "weight": 8, "target": 5},
            {"name": "Slow / non-moving stock items reviewed", "unit": "Count", "weight": 6, "target": 30},
            {"name": "Lifting tackles inspections", "unit": "Count", "weight": 6, "target": 8},
            {"name": "5S / housekeeping checks", "unit": "Count", "weight": 8, "target": 12},
            {"name": "ERP transactions posted same-day", "unit": "Count", "weight": 6, "target": 60},
            {"name": "PRs raised for replenishment", "unit": "Count", "weight": 6, "target": 8},
        ],
    },
    {
        "email": "p.velu92@gmail.com",
        "name": "VELAYUTHAM P",
        "designation": "Site Manager",
        "department": "Projects (Site)",
        "reports_to": "AGM Projects",
        "is_admin": False,
        "kpis": [
            {"name": "Project milestones achieved", "unit": "Count", "weight": 12, "target": 8},
            {"name": "Tonnage erected at site", "unit": "MT", "weight": 12, "target": 200},
            {"name": "Material consignments verified", "unit": "Count", "weight": 8, "target": 12},
            {"name": "QC inspections cleared (first attempt)", "unit": "Count", "weight": 10, "target": 30},
            {"name": "Snag list items closed", "unit": "Count", "weight": 8, "target": 25},
            {"name": "EHS audits / safety walks", "unit": "Count", "weight": 10, "target": 18},
            {"name": "Sub-contractor reviews", "unit": "Count", "weight": 8, "target": 10},
            {"name": "DPRs (Daily Progress Reports) submitted", "unit": "Count", "weight": 10, "target": 22},
            {"name": "Client RFIs / approvals closed", "unit": "Count", "weight": 8, "target": 10},
            {"name": "Variation / change orders captured", "unit": "Count", "weight": 6, "target": 6},
            {"name": "Billing measurement sheets submitted", "unit": "Count", "weight": 8, "target": 8},
        ],
    },
    {
        "email": "lokeshel79@gmail.com",
        "name": "Lokesh",
        "designation": "Site Engineer",
        "department": "Projects (Site)",
        "reports_to": "Site Manager",
        "is_admin": False,
        "kpis": [
            {"name": "DPRs submitted on-time", "unit": "Count", "weight": 12, "target": 22},
            {"name": "Drawing compliance checks", "unit": "Count", "weight": 8, "target": 22},
            {"name": "Tonnage / bays erected", "unit": "MT", "weight": 12, "target": 100},
            {"name": "Material receipts verified", "unit": "Count", "weight": 8, "target": 8},
            {"name": "Material indents processed", "unit": "Count", "weight": 8, "target": 22},
            {"name": "Quality inspections cleared", "unit": "Count", "weight": 10, "target": 25},
            {"name": "WIRs / RFIs raised", "unit": "Count", "weight": 8, "target": 15},
            {"name": "NCRs closed", "unit": "Count", "weight": 8, "target": 6},
            {"name": "Bolt torque / alignment records logged", "unit": "Count", "weight": 8, "target": 30},
            {"name": "Safety / PPE compliance checks", "unit": "Count", "weight": 8, "target": 22},
            {"name": "Toolbox talks (TBTs) conducted", "unit": "Count", "weight": 6, "target": 22},
            {"name": "Snag list items closed in own area", "unit": "Count", "weight": 4, "target": 15},
        ],
    },
    {
        "email": "robinjkl84@yahoo.com",
        "name": "Robin James",
        "designation": "Site Engineer",
        "department": "Projects (Site)",
        "reports_to": "Site Manager",
        "is_admin": False,
        "kpis": [
            {"name": "DPRs submitted on-time", "unit": "Count", "weight": 12, "target": 22},
            {"name": "Drawing compliance checks", "unit": "Count", "weight": 8, "target": 22},
            {"name": "Tonnage / bays erected", "unit": "MT", "weight": 12, "target": 100},
            {"name": "Material receipts verified", "unit": "Count", "weight": 8, "target": 8},
            {"name": "Material indents processed", "unit": "Count", "weight": 8, "target": 22},
            {"name": "Quality inspections cleared", "unit": "Count", "weight": 10, "target": 25},
            {"name": "WIRs / RFIs raised", "unit": "Count", "weight": 8, "target": 15},
            {"name": "NCRs closed", "unit": "Count", "weight": 8, "target": 6},
            {"name": "Bolt torque / alignment records logged", "unit": "Count", "weight": 8, "target": 30},
            {"name": "Safety / PPE compliance checks", "unit": "Count", "weight": 8, "target": 22},
            {"name": "Toolbox talks (TBTs) conducted", "unit": "Count", "weight": 6, "target": 22},
            {"name": "Snag list items closed in own area", "unit": "Count", "weight": 4, "target": 15},
        ],
    },

    # ============================================================
    # 4 NEW EMPLOYEES (Round 4 - Site team additions)
    # All personal emails — Azure Guest invites needed
    # ============================================================
    {
        "email": "renjithrj970@gmail.com",
        "name": "Renjith Kumar",
        "designation": "Junior Safety Officer",
        "department": "Environment, Health & Safety",
        "reports_to": "Safety Officer",
        "is_admin": False,
        "kpis": [
            {"name": "Safety inspections / walks done", "unit": "Count", "weight": 12, "target": 22},
            {"name": "Work permits issued & audited", "unit": "Count", "weight": 10, "target": 25},
            {"name": "PPE compliance checks done", "unit": "Count", "weight": 8, "target": 22},
            {"name": "EHS inductions conducted for new joiners", "unit": "Count", "weight": 8, "target": 10},
            {"name": "Toolbox talks (TBTs) conducted", "unit": "Count", "weight": 10, "target": 22},
            {"name": "Near-miss reports logged", "unit": "Count", "weight": 8, "target": 4},
            {"name": "BBS observations logged", "unit": "Count", "weight": 10, "target": 60},
            {"name": "Incident field data submissions", "unit": "Count", "weight": 8, "target": 3},
            {"name": "CAPAs closed", "unit": "Count", "weight": 10, "target": 8},
            {"name": "Emergency drills conducted", "unit": "Count", "weight": 8, "target": 2},
            {"name": "EHS records updated same-day", "unit": "Count", "weight": 8, "target": 22},
        ],
    },
    {
        "email": "nandakumar250788@gmail.com",
        "name": "Nanda Kumar",
        "designation": "Project Engineer (Civil)",
        "department": "Projects (Civil)",
        "reports_to": "Site Manager",
        "is_admin": False,
        "kpis": [
            {"name": "Civil DPRs submitted on-time", "unit": "Count", "weight": 12, "target": 22},
            {"name": "Foundations / pedestals completed", "unit": "Count", "weight": 12, "target": 12},
            {"name": "Anchor bolt groups verified in tolerance", "unit": "Count", "weight": 10, "target": 8},
            {"name": "Foundations handed over to PEB erection", "unit": "Count", "weight": 10, "target": 8},
            {"name": "Concrete cube tests passed", "unit": "Count", "weight": 10, "target": 30},
            {"name": "Pre-pour inspections cleared first-attempt", "unit": "Count", "weight": 8, "target": 20},
            {"name": "Material consignments verified", "unit": "Count", "weight": 8, "target": 12},
            {"name": "WIRs / RFIs raised", "unit": "Count", "weight": 6, "target": 15},
            {"name": "NCRs closed", "unit": "Count", "weight": 6, "target": 6},
            {"name": "Snag list items closed", "unit": "Count", "weight": 8, "target": 25},
            {"name": "Subcontractor RA bills certified", "unit": "Count", "weight": 6, "target": 8},
            {"name": "Site records updated same-day", "unit": "Count", "weight": 4, "target": 22},
        ],
    },
    {
        "email": "lrajasekar1984@gmail.com",
        "name": "Rajasekar L",
        "designation": "Site Supervisor",
        "department": "Projects (Site)",
        "reports_to": "Site Manager",
        "is_admin": False,
        "kpis": [
            {"name": "Project milestones completed (zone)", "unit": "Count", "weight": 10, "target": 8},
            {"name": "Tonnes erected at site", "unit": "MT", "weight": 12, "target": 150},
            {"name": "Bays completed vs plan", "unit": "Count", "weight": 10, "target": 8},
            {"name": "Quality inspections cleared first-attempt", "unit": "Count", "weight": 8, "target": 25},
            {"name": "Snag items closed in own zone", "unit": "Count", "weight": 8, "target": 20},
            {"name": "Safety / PPE compliance checks", "unit": "Count", "weight": 10, "target": 22},
            {"name": "Toolbox talks conducted", "unit": "Count", "weight": 8, "target": 22},
            {"name": "Near-miss reports logged", "unit": "Count", "weight": 8, "target": 2},
            {"name": "Material consignments reconciled", "unit": "Count", "weight": 6, "target": 12},
            {"name": "DPRs submitted on-time", "unit": "Count", "weight": 10, "target": 22},
            {"name": "EHS / quality records updated same-day", "unit": "Count", "weight": 10, "target": 22},
        ],
    },
    {
        "email": "mohan2681@gmail.com",
        "name": "M. Mohan Kumar",
        "designation": "Junior Engineer (Civil)",
        "department": "Projects (Civil)",
        "reports_to": "Project Engineer (Civil)",
        "is_admin": False,
        "kpis": [
            {"name": "Daily progress notes (DPN) submitted on-time", "unit": "Count", "weight": 10, "target": 22},
            {"name": "Layouts / levels / grid checks done", "unit": "Count", "weight": 8, "target": 15},
            {"name": "Excavations supervised with permits", "unit": "Count", "weight": 8, "target": 8},
            {"name": "Pre-pour checklists signed off", "unit": "Count", "weight": 10, "target": 12},
            {"name": "Concrete pours attended end-to-end", "unit": "Count", "weight": 10, "target": 12},
            {"name": "Curing logs maintained", "unit": "Count", "weight": 8, "target": 22},
            {"name": "Anchor bolt template verifications", "unit": "Count", "weight": 8, "target": 8},
            {"name": "Material receipts tallied", "unit": "Count", "weight": 8, "target": 12},
            {"name": "Material issue register updates", "unit": "Count", "weight": 6, "target": 22},
            {"name": "Site registers updated same-day", "unit": "Count", "weight": 8, "target": 22},
            {"name": "Snag items closed", "unit": "Count", "weight": 8, "target": 12},
            {"name": "PPE / TBT compliance for own gang", "unit": "Count", "weight": 8, "target": 22},
        ],
    },
]

# Admin-only accounts (no KPIs)
ADMIN_ONLY_ACCOUNTS = [
    {
        "email": "info@metfraa.com",
        "name": "Metfraa Admin",
        "designation": "System Administrator",
        "department": "Administration",
        "is_admin": True,
    },
    {
        "email": "arasu@metfraa.com",
        "name": "Arasu",
        "designation": "Managing Director",
        "department": "Management",
        "is_admin": True,
    },
]
